using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Xml.Linq;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Heat.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
	public sealed partial class thermalunit : IMigrationMetadata
	{

		private readonly ResourceManager Resources = new ResourceManager(typeof(thermalunit));

		//Private ReadOnly Property IMigrationMetadata_Id() As String Implements IMigrationMetadata.Id
		//    Get
		//        Return "201508311231239_thermalunit"
		//    End Get
		//End Property

		//Private ReadOnly Property IMigrationMetadata_Source() As String Implements IMigrationMetadata.Source
		//    Get
		//        Return Resources.GetString("Source")
		//    End Get
		//End Property

		//Private ReadOnly Property IMigrationMetadata_Target() As String Implements IMigrationMetadata.Target
		//    Get
		//        Return Resources.GetString("Target")
		//    End Get
		//End Property
	}
}
