// <auto-generated />
namespace Heat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class virtualaddressproposedcalls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(virtualaddressproposedcalls));
        
        string IMigrationMetadata.Id
        {
            get { return "201601021300596_virtual-address-proposedcalls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
